### PR TITLE
Issue 21292: Link the files directly on s3, using HTTPS

### PR DESCRIPTION
**Pull request by Geod24**
I'll also submit a companion PR on dlang.org to link to the files directly.

### CODE REVIEW

**Comment by Geod24** [comment]
@MartinNowak : I couldn't test this, since I don't have access to s3. This has been preventing users from downloading (without any error message) for a few months now, so hopefully we can get this fixed soon (although the dlang.org PR will be the most impactful for users).

**Comment by PetarKirov** [comment]
@MartinNowak how about putting the S3 bucket behind a CloudFlare DNS + HTTPS proxy?

**Comment by MartinNowak** [comment]
> @MartinNowak how about putting the S3 bucket behind a CloudFlare DNS + HTTPS proxy?

Seems weird to sell dlang users to Cloudflare  (plus their occasional fuckups) just for adding a MITMed https for already cryptographically signed downloads.

**Comment by MartinNowak** [comment]
Symlinks no longer seem to work on the S3 (REST API) endpoints. So this makes quite a few things less maintainable.
Not too big a fan of deploying plenty of fancy services, given how many people are already involved with coordinating DNS (Jan Knepper), website (@CyberShadow, @andralex, etc.), downloads (@braddr), and releases (@MartinNowak).

It seems to be a given that we need to move off http downloads for Windows users.
[21292 – Chrome by default now blocks downloading .dmg or .exe files via HTTP](https://issues.dlang.org/show_bug.cgi?id=21292)

Could we maybe just reuse the existing website infrastructure, i.e. migrate http://downloads.dlang.org/ (only the website) to https://dlang.org/downloads/ (or so).
Then we might be able to add a few redirects ([dlang.org/.htaccess](https://github.com/dlang/dlang.org/blob/6774f6d7a5c3ff1282d852b479676c042f7a6d2b/.htaccess)) for the actual downloads from `https://s3.$region.amazonaws...`, without adding maintenance overhead due to leaky s3 links and lack of redirects.
We already do update the website as part of the [release process](https://gist.github.com/MartinNowak/a471fe7ddbfeef205cdf04c93a94c6d0), so at least that wouldn't introduce new components or steps.

I guess we could also swap the `2.x/2.095.0/file -> 2021/file` redirects to either `2021/file -> 2.x/2.095.0/file` or drop them entirely.
That would make download redirects/links easier and more stable.
The year structure was mostly a setup of @braddr, who sponsors the bucket, to structure the archive, but might not be that important for 2.x.
We did save all of those redirects in [`make-links`](https://github.com/dlang/downloads.dlang.org/blob/cf333604370171ecd5ffe6da2461fcc43ba722b3/make-links). But shouldn't be too much scripting to restructure the 2.x downloads and write/generate an Apache redirect file.
I also think it'd be fine to let the 1.x stuff be an archive and not update it.

Alternatives considered:
- Setup some HTTPS proxy in front of S3 (AWS Cloudfront, Cloudflare) (who maintains and integrates this?)
- Leave http://downloads.dlang.org/ as is, from my understanding [21292 – Chrome by default now blocks downloading .dmg or .exe files via HTTP](https://issues.dlang.org/show_bug.cgi?id=21292) is coming from mixed-content, not from HTTP
  ([Chromium Blog: Protecting users from insecure downloads in Google Chrome](https://blog.chromium.org/2020/02/protecting-users-from-insecure.html)) (might run into problems in the future, but might be OKish as archive)
- Find some new CDN service (who maintains and migrates this?)
- Provide releases via OS packaging services (who maintains and coordinates all the integrations?)

**Comment by MartinNowak** [comment]
Just to emphasize my understanding, there is no **urgent** need for action here, since [21292 – Chrome by default now blocks downloading .dmg or .exe files via HTTP](https://issues.dlang.org/show_bug.cgi?id=21292) seems to be a mixed-content problem and is fixed by https://github.com/dlang/dlang.org/pull/2933. *This* PR is mostly an upgrade of the release archive to work from AWS S3's TLS endpoints and might prevent problems with future browser deprecations of HTTP.
Since redirects no longer seem to work for AWS S3's TLS endpoints, we'd need to restructure our release archive. Otherwise this change would break downloads by version (e.g. http://downloads.dlang.org/releases/2.x/2.095.0/).
Hence as per https://github.com/dlang/downloads.dlang.org/pull/6#issuecomment-777090957, I'd suggest to tune our approach somewhat for maintainability.

If this problem is indeed more urgent, please notify me @MartinNowak

**Comment by ibuclaw** [comment]
The dlang foundation has decided to move all downloads to backblaze, with cloudflare as the front for web traffic - they are footing the bill for it ($2 or less per month).  This solves the HTTPS problem for accessing downloads via https://downloads.dlang.org.

IIUC, this PR is now redundant.

**Pull request closed without merging**
